"""empty message

Revision ID: 5261437ce96e
Revises: None
Create Date: 2014-07-25 12:46:36.925190

"""

# revision identifiers, used by Alembic.
revision = '5261437ce96e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('Staff_Name', sa.String(length=500), nullable=True),
    sa.Column('Staff_ID', sa.String(length=500), nullable=True),
    sa.Column('Staff_Email', sa.String(length=500), nullable=True),
    sa.Column('Staff_Phone', sa.Integer(), nullable=True),
    sa.Column('Staff_Address', sa.Text(), nullable=True),
    sa.Column('Staff_Photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SID'),
    sa.UniqueConstraint('Staff_Phone')
    )
    op.create_index(op.f('ix_Staff_Staff_ID'), 'Staff', ['Staff_ID'], unique=True)
    op.create_index(op.f('ix_Staff_Staff_Name'), 'Staff', ['Staff_Name'], unique=False)
    op.create_table('Publications',
    sa.Column('PID', sa.Integer(), nullable=False),
    sa.Column('SID_Pub', sa.Integer(), nullable=True),
    sa.Column('Pub_Title', sa.String(length=500), nullable=True),
    sa.Column('Pub_Year', sa.Integer(), nullable=True),
    sa.Column('Pub_Attach', sa.Text(), nullable=True),
    sa.Column('Pub_Title1', sa.String(length=500), nullable=True),
    sa.Column('Pub_Year1', sa.Integer(), nullable=True),
    sa.Column('Pub_Attach1', sa.Text(), nullable=True),
    sa.Column('Pub_Title2', sa.String(length=500), nullable=True),
    sa.Column('Pub_Year2', sa.Integer(), nullable=True),
    sa.Column('Pub_Attach2', sa.Text(), nullable=True),
    sa.Column('Pub_Title3', sa.String(length=500), nullable=True),
    sa.Column('Pub_Year3', sa.Integer(), nullable=True),
    sa.Column('Pub_Attach3', sa.Text(), nullable=True),
    sa.Column('Pub_Title4', sa.String(length=500), nullable=True),
    sa.Column('Pub_Year4', sa.Integer(), nullable=True),
    sa.Column('Pub_Attach4', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Pub'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('PID')
    )
    op.create_index(op.f('ix_Publications_Pub_Year'), 'Publications', ['Pub_Year'], unique=False)
    op.create_index(op.f('ix_Publications_Pub_Year1'), 'Publications', ['Pub_Year1'], unique=False)
    op.create_index(op.f('ix_Publications_Pub_Year2'), 'Publications', ['Pub_Year2'], unique=False)
    op.create_index(op.f('ix_Publications_Pub_Year3'), 'Publications', ['Pub_Year3'], unique=False)
    op.create_index(op.f('ix_Publications_Pub_Year4'), 'Publications', ['Pub_Year4'], unique=False)
    op.create_table('GuestLecture',
    sa.Column('PID', sa.Integer(), nullable=False),
    sa.Column('SID_Glec', sa.Integer(), nullable=True),
    sa.Column('GLec_Name', sa.String(length=500), nullable=True),
    sa.Column('GLec_Topic', sa.String(length=500), nullable=True),
    sa.Column('GLec_Year', sa.Integer(), nullable=True),
    sa.Column('GLec_Name1', sa.String(length=500), nullable=True),
    sa.Column('GLec_Topic1', sa.String(length=500), nullable=True),
    sa.Column('GLec_Year1', sa.Integer(), nullable=True),
    sa.Column('GLec_Name2', sa.String(length=500), nullable=True),
    sa.Column('GLec_Topic2', sa.String(length=500), nullable=True),
    sa.Column('GLec_Year2', sa.Integer(), nullable=True),
    sa.Column('GLec_Name3', sa.String(length=500), nullable=True),
    sa.Column('GLec_Topic3', sa.String(length=500), nullable=True),
    sa.Column('GLec_Year3', sa.Integer(), nullable=True),
    sa.Column('GLec_Name4', sa.String(length=500), nullable=True),
    sa.Column('GLec_Topic4', sa.String(length=500), nullable=True),
    sa.Column('GLec_Year4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Glec'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('PID')
    )
    op.create_index(op.f('ix_GuestLecture_GLec_Year'), 'GuestLecture', ['GLec_Year'], unique=False)
    op.create_index(op.f('ix_GuestLecture_GLec_Year1'), 'GuestLecture', ['GLec_Year1'], unique=False)
    op.create_index(op.f('ix_GuestLecture_GLec_Year2'), 'GuestLecture', ['GLec_Year2'], unique=False)
    op.create_index(op.f('ix_GuestLecture_GLec_Year3'), 'GuestLecture', ['GLec_Year3'], unique=False)
    op.create_index(op.f('ix_GuestLecture_GLec_Year4'), 'GuestLecture', ['GLec_Year4'], unique=False)
    op.create_table('Others',
    sa.Column('OID', sa.Integer(), nullable=False),
    sa.Column('SID_Others', sa.Integer(), nullable=True),
    sa.Column('Others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Others'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('OID')
    )
    op.create_table('Re_bodies_awards',
    sa.Column('RID', sa.Integer(), nullable=False),
    sa.Column('SID_Res', sa.Integer(), nullable=True),
    sa.Column('Research', sa.Text(), nullable=True),
    sa.Column('ProfBodies', sa.Text(), nullable=True),
    sa.Column('Awards', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Res'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('RID')
    )
    op.create_table('Experience',
    sa.Column('ExID', sa.Integer(), nullable=False),
    sa.Column('SID_Exp', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_Name', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_Desig', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_FYear', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_TYear', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_Name1', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_Desig1', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_FYear1', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_TYear1', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_Name2', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_Desig2', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_FYear2', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_TYear2', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_Name3', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_Desig3', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_FYear3', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_TYear3', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_Name4', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_Desig4', sa.String(length=500), nullable=True),
    sa.Column('TeachingExp_FYear4', sa.Integer(), nullable=True),
    sa.Column('TeachingExp_TYear4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Exp'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('ExID')
    )
    op.create_table('BookPublications',
    sa.Column('BID', sa.Integer(), nullable=False),
    sa.Column('SID_Book', sa.Integer(), nullable=True),
    sa.Column('Book_Name', sa.String(length=500), nullable=True),
    sa.Column('Book_Pub', sa.String(length=500), nullable=True),
    sa.Column('Book_ISBN', sa.String(length=500), nullable=True),
    sa.Column('Book_Year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Book'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('BID')
    )
    op.create_index(op.f('ix_BookPublications_Book_Year'), 'BookPublications', ['Book_Year'], unique=False)
    op.create_table('Activities',
    sa.Column('AID', sa.Integer(), nullable=False),
    sa.Column('SID_Act', sa.Integer(), nullable=True),
    sa.Column('Workshops', sa.Text(), nullable=True),
    sa.Column('Seminars', sa.Text(), nullable=True),
    sa.Column('EDP', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Act'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('AID')
    )
    op.create_table('Education',
    sa.Column('EID', sa.Integer(), nullable=False),
    sa.Column('SID_Edu', sa.Integer(), nullable=True),
    sa.Column('UG_Ins_Name', sa.String(length=500), nullable=True),
    sa.Column('UG_Ins_Special', sa.String(length=500), nullable=True),
    sa.Column('UG_Ins_Year', sa.Integer(), nullable=True),
    sa.Column('UG_Attach', sa.Text(), nullable=True),
    sa.Column('PG_Ins_Name', sa.String(length=500), nullable=True),
    sa.Column('PG_Ins_Special', sa.String(length=500), nullable=True),
    sa.Column('PG_Ins_Year', sa.Integer(), nullable=True),
    sa.Column('PG_Attach', sa.Text(), nullable=True),
    sa.Column('PHD_Ins_Name', sa.String(length=500), nullable=True),
    sa.Column('PHD_Ins_Special', sa.String(length=500), nullable=True),
    sa.Column('PHD_Ins_Year', sa.Integer(), nullable=True),
    sa.Column('PHD_Attach', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SID_Edu'], ['Staff.SID'], ),
    sa.PrimaryKeyConstraint('EID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Education')
    op.drop_table('Activities')
    op.drop_index(op.f('ix_BookPublications_Book_Year'), table_name='BookPublications')
    op.drop_table('BookPublications')
    op.drop_table('Experience')
    op.drop_table('Re_bodies_awards')
    op.drop_table('Others')
    op.drop_index(op.f('ix_GuestLecture_GLec_Year4'), table_name='GuestLecture')
    op.drop_index(op.f('ix_GuestLecture_GLec_Year3'), table_name='GuestLecture')
    op.drop_index(op.f('ix_GuestLecture_GLec_Year2'), table_name='GuestLecture')
    op.drop_index(op.f('ix_GuestLecture_GLec_Year1'), table_name='GuestLecture')
    op.drop_index(op.f('ix_GuestLecture_GLec_Year'), table_name='GuestLecture')
    op.drop_table('GuestLecture')
    op.drop_index(op.f('ix_Publications_Pub_Year4'), table_name='Publications')
    op.drop_index(op.f('ix_Publications_Pub_Year3'), table_name='Publications')
    op.drop_index(op.f('ix_Publications_Pub_Year2'), table_name='Publications')
    op.drop_index(op.f('ix_Publications_Pub_Year1'), table_name='Publications')
    op.drop_index(op.f('ix_Publications_Pub_Year'), table_name='Publications')
    op.drop_table('Publications')
    op.drop_index(op.f('ix_Staff_Staff_Name'), table_name='Staff')
    op.drop_index(op.f('ix_Staff_Staff_ID'), table_name='Staff')
    op.drop_table('Staff')
    ### end Alembic commands ###
